scope: suta-ha001
namespace: /service/
name: pg-ha-1

restapi:
  listen: 172.31.4.103:8008
  connect_address: 172.31.4.103:8008

etcd3:
  hosts: 172.31.8.151:2379,172.31.12.181:2379,172.31.1.168:2379
  protocol: http
  cacert: /etc/patroni/etcd-ca.crt
  cert: /etc/patroni/etcd-client.crt
  key: /etc/patroni/etcd-client.key
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        max_wal_senders: 10
        max_replication_slots: 10

  initdb:
    - encoding: UTF8
    - data-checksums

  pg_hba:
    - local all all trust
    - host all all 172.31.4.103/32 scram-sha-256
    - host all all 172.31.6.248/32 scram-sha-256
    - host all all 172.31.5.186/32 scram-sha-256
    - host replication replicator 172.31.4.103/32 scram-sha-256
    - host replication replicator 172.31.6.248/32 scram-sha-256
    - host replication replicator 172.31.5.186/32 scram-sha-256
    - host mattermost mattermost 172.31.11.231/32 scram-sha-256
postgresql:
  listen: 172.31.4.103:5432
  connect_address: 172.31.4.103:5432
  data_dir: /opt/pgsql/data
  bin_dir: /usr/bin
  pgpass: /etc/patroni/pgpass

  authentication:
    superuser:
      username: postgres
      password: "<REDACTED>"
    replication:
      username: replicator
      password: "<REDACTED>"

  parameters:
    unix_socket_directories: /var/run/postgresql
    password_encryption: scram-sha-256

  create_replica_methods:
    - basebackup

  basebackup:
    checkpoint: fast

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
